services:
  postgres-db:
    image: postgres:13
    container_name: planetaestacionamiento-postgres
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE
    ports:
      - "5433:5432"
    volumes:
      - ./backend/db/db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB_DATABASE"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  app:
    build: .
    container_name: planetaestacionamiento-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      postgres-db:
        condition: service_healthy
    links:
      - postgres-db
    environment:
      DB_HOST: postgres-db
    env_file:
      - ./.env

